### ISSUE TITLE
Hard-coded links

### ISSUE THREAD

**Issue by ashitikov** [Andrei-III/troll_updater#1]
Using direct hard-coded links is really unstable thing. Is there some troll-game api that providing links to download modules? In case of link changing user have to update troll_updater and only then update modules :)

https://github.com/Andrei-III/troll_updater/blob/3e93acc6f115455bc82e0b8ee3c4a6ea14710078/troll_updater.py#L486-L491

--
VenT

**Comment by Andrei-III** [comment]
I agree with you. I also thought about this, although I didn't want to
complicate things for KingArthur with that many APIs.

We'll probably make it dynamic in the near future. I'll send KA a message
one of these days. If you have any more suggestions, please send them to
me.

Thanks,

Andrei

**Comment by Andrei-III** [comment]
The updater no longer uses hardcoded links but relies on a JSON provided by TrollGame to display available addons and their versions. That should solve the problem.

**Comment by ashitikov** [comment]
Good job, thank you!
